// examples/angular/src/modules/text-field/text-field.component.ts
import { Component } from '@angular/core';
import { register, LeTextField, SeTextField } from 'awesome-components';

register(LeTextField, SeTextField);

@Component({
  standalone: true,
  template: `
    <le-text-field [value]="text" (input)="inputText($event)"></le-text-field>
    <le-text-field [value]="text" (input)="inputText($event)"></le-text-field>

    <se-text-field [value]="text" (input)="inputText($event)"></se-text-field>
    <se-text-field [value]="text" (input)="inputText($event)"></se-text-field>

    {{ text }}
  `,
})
export class TextFieldComponent {
  text = '';

  inputText(event: Event) {
    this.text = (event.target as HTMLInputElement).value;
  }
}

// examples/svelte/src/modules/text-field/TextField.svelte
<script lang="ts">
  import { register, LeTextField, SeTextField } from 'awesome-components';

  register(LeTextField, SeTextField);

  const flux = {
    text: '',
    inputText(event: Event) {
      flux.text = (event.target as HTMLInputElement).value;
    },
  };
</script>

<le-text-field value={flux.text} on:input={flux.inputText} />

<se-text-field value={flux.text} on:input={flux.inputText} />

{flux.text}
