// examples/vue/src/modules/text-field/TextField.vue
<script lang="ts" setup>
import { reactive } from 'vue';
import { LeTextField, SeTextField } from 'awesome-components';

const flux = reactive({
  text: '',
  inputText(event: Event) {
    flux.text = (event.target as HTMLInputElement).value;
  },
});
</script>

<template>
  <le-text-field :value="flux.text" @input="flux.inputText"></le-text-field>

  <se-text-field :value="flux.text" @input="flux.inputText"></se-text-field>

  {{ flux.text }}
</template>

// examples/svelte/src/modules/text-field/TextField.svelte
<script lang="ts">
  import { register, LeTextField, SeTextField } from 'awesome-components';

  register(LeTextField, SeTextField);

  const flux = {
    text: '',
    inputText(event: Event) {
      flux.text = (event.target as HTMLInputElement).value;
    },
  };
</script>

<le-text-field value={flux.text} on:input={flux.inputText} />

<se-text-field value={flux.text} on:input={flux.inputText} />

{flux.text}
