// examples/react/src/modules/text-field/TextField.tsx
import React, { useState } from 'react';
import { register, LeTextField, SeTextField } from 'awesome-components';

register(LeTextField, SeTextField);

export default () => {
  const [text, setText] = useState('');

  return (
    <>
      <le-text-field
        value={text}
        onInput={(event: Event) => setText((event.target as HTMLInputElement).value)}
      ></le-text-field>

      <se-text-field
        value={text}
        onInput={(event: Event) => setText((event.target as HTMLInputElement).value)}
      ></se-text-field>

      {text}
    </>
  );
};

// examples/svelte/src/modules/text-field/TextField.svelte
<script lang="ts">
  import { register, LeTextField, SeTextField } from 'awesome-components';

  register(LeTextField, SeTextField);

  const flux = {
    text: '',
    inputText(event: Event) {
      flux.text = (event.target as HTMLInputElement).value;
    },
  };
</script>

<le-text-field value={flux.text} on:input={flux.inputText} />

<se-text-field value={flux.text} on:input={flux.inputText} />

{flux.text}
