// examples/preact/src/App.tsx
import { useState } from 'preact/hooks';
import { SimpleGreeting, MyButton } from '../../../dist/awesome-components';

import { Foo } from './Foo';

SimpleGreeting;
MyButton;

export function App() {
  const [myLabel, setMyLabel] = useState('');

  const myClick = (event) => {
    console.log(event);
    setMyLabel(event.detail.label);
  };

  return (
    <>
      <simple-greeting name="World"></simple-greeting>
      <Foo />

      <my-button onmyClick={myClick}></my-button>
      {myLabel}
    </>
  );
}

// examples/svelte/src/App.svelte
<script lang="ts">
  import { SimpleGreeting, MyButton } from '../../../dist/awesome-components';

  import Foo from './Foo.svelte';

  let myLabel = '';

  const myClick = (event: CustomEvent) => {
    console.log(event);
    myLabel = event.detail.label;
  };
</script>

<simple-greeting name="World"></simple-greeting>
<Foo />

<my-button on:myClick={myClick}>My Click</my-button>
{myLabel}
